### PR TITLE
[+1] ORS Liver - flow rate sprite

### PR DESCRIPTION
**Pull request by plouiegps**
https://blacklinegps.atlassian.net/browse/SW-9664

The only file worth code reviewing is: ```sprites-general.less```

Related: https://github.com/blackline/icarus/pull/2486

### CODE REVIEW

**Comment by bdgregor** [comment]
:+1:

**Comment by ji-zhou-bln** [comment]
:+1:

**Comment by amuegge** [comment]
DON'T TRUST JI!  That guy is deadly.  Additionally - please unsubscribe me from this and the keys, should i still be in there :)

Thanks!

**Comment by rayl** [comment]
@amuegge well that's interesting... no sign of you anywhere in the admin panels, seems github is slightly b0rken here.  i'll chase this down tomorrow.

have you been getting any other spam from us?

**Comment by plouiegps** [comment]
@rayl This is a public repo. So meh?

**Comment by rayl** [comment]
yah, i think the issue is that @amuegge is still watching this repo.  i didn't see a way to unwatch him, so i think he'll need to do that himself.

**Pull request merged**
